// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkp0W5fb1L-5443b0vc3VlYMmqNvfxVKs',
    appId: '1:743232584431:web:1f811d0fc9e09b280e791a',
    messagingSenderId: '743232584431',
    projectId: 'walletmyproject',
    authDomain: 'walletmyproject.firebaseapp.com',
    storageBucket: 'walletmyproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNhwpXzTNjwNSvavC77qk1omw6JMFUfJ8',
    appId: '1:743232584431:android:0be9a211fcb9d6120e791a',
    messagingSenderId: '743232584431',
    projectId: 'walletmyproject',
    storageBucket: 'walletmyproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4biCyVJCeQCcO0iAd2Ccb-vHPjuR_NDk',
    appId: '1:743232584431:ios:0844792dc107e2550e791a',
    messagingSenderId: '743232584431',
    projectId: 'walletmyproject',
    storageBucket: 'walletmyproject.appspot.com',
    iosBundleId: 'com.example.flutterApplication1IntrodectionMyWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4biCyVJCeQCcO0iAd2Ccb-vHPjuR_NDk',
    appId: '1:743232584431:ios:0844792dc107e2550e791a',
    messagingSenderId: '743232584431',
    projectId: 'walletmyproject',
    storageBucket: 'walletmyproject.appspot.com',
    iosBundleId: 'com.example.flutterApplication1IntrodectionMyWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkp0W5fb1L-5443b0vc3VlYMmqNvfxVKs',
    appId: '1:743232584431:web:eb4c1786156619610e791a',
    messagingSenderId: '743232584431',
    projectId: 'walletmyproject',
    authDomain: 'walletmyproject.firebaseapp.com',
    storageBucket: 'walletmyproject.appspot.com',
  );
}
